version: "3"

services:

  web:
    image: nginx:mainline-alpine
    ports:
      - "80:80"
      - "443:443"
    read_only: true
    restart: unless-stopped
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ./volumes/web/cert:/cert:ro
      - ./volumes/web/ssl:/etc/nginx/sites-available:ro
      - ./volumes/web/conf:/etc/nginx/conf.d:rw
      - ./volumes/web/cache:/var/cache/nginx:rw
      - ./volumes/web/run:/var/run:rw
      - ./volumes/web/bin/entrypoint.sh:/entrypoint.sh
      - /etc/localtime:/etc/localtime
    # Uncomment for SSL
    environment:
    #  - MATTERMOST_ENABLE_SSL=true
      - APP_HOST=maithanam.c.vast-math-202912.internal
      - APP_PORT_NUMBER=8000
    command: /bin/bash -c "rm /etc/nginx/conf.d/default.conf && apk add --no-cache curl"
    entrypoint: /entrypoint.sh
